### ISSUE TITLE
failed to initialize

### ISSUE THREAD

**Issue by ghost** [luanpotter/vscode-dart-import#2]
keep getting this error when trying to run the extension: 

> Failed to initialize extension. Is this a valid Dart/Flutter project?

my flutter doctor result:

> [√] Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17763.292], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [!] Android Studio (version 3.3)
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
> [√] VS Code (version 1.31.0)
> [!] Connected device
>     ! No devices available

**Comment by luanpotter** [comment]
Hi, @runedrune ! This plugin works by finding the pubspec.yaml file in the root of the project you opened. It does that to find out your project name. Make sure you have actually opened your root folder on VSCode.

**Comment by ghost** [comment]
This seems to be the actual error: 
`Expected line 'name:' on pubspec.yaml to match regex, but it didn't (line: name: jaiza
).`

Not sure what's wrong. It was working before.

**Comment by luanpotter** [comment]
The Regex it's trying to match is this: `/^\s*name:\s*(.*)$/`

Maybe there is something unexpected inside your pubspec file...

I suspect it's a trailling space, please check your pubspec file, according to the error message there is an extra space after your project name.

However upon quick check of the regex it doesn't look like it should matter much; so, in case the error persist, could you please send the file so we can understand what's the issue?

**Comment by ghost** [comment]
Strange. I've checked everything. Maybe I'm missing something right in front of me. Here's the complete file:

```
name: jaiza
description: A flutter app to access the Jamaat e Islami Jaiza website.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.15.7
  http: ^0.12.0
  firebase_messaging: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
```
